include:
  - board: nice_nano_v2
    shield: splitkb_aurora_corne_left
    snippets: [ "studio_5col" ]  # Dies aktiviert das 5-Spalten-Layout
    extra-modules: [ "config/zmk-pointing" ]
  - board: nice_nano_v2
    shield: splitkb_aurora_corne_right
    snippets: [ "studio_5col" ]  # Dies aktiviert das 5-Spalten-Layout
    extra-modules: [ "config/zmk-pointing" ]
