manifest:
  remotes:
    - name: zmk-pointing
      url-base: https://github.com/zmk-pointing
  projects:
    - name: zmk
      remote: zmk-pointing
      revision: main
      import: app/west.yml
  self:
    path: config
